---
- name: Update apt cache (on Debian).
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == 'Debian'

- name: Install required packages for automysqlbackup
  ansible.builtin.package:
    name: "{{ automysqlbackup_packages }}"
    state: present
  tags:
    - packages
