{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

RUN if [ `which apt-get` ]; then apt-get update && apt-get upgrade -y && apt-get install -y systemd systemd-sysv python3 sudo bash ca-certificates && apt-get clean; \
    elif [ `which dnf` ]; then dnf makecache && dnf --assumeyes install python sudo python-devel python2-dnf bash && dnf clean all; \
    elif [ `which yum` ]; then yum makecache fast && yum update -y && yum remove -y subscription-manager && yum install -y python sudo yum-plugin-ovl bash systemd-sysv || true && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all; \
    elif [ `which zypper` ]; then zypper refresh && zypper update -y && zypper install -y python sudo bash python-xml && zypper clean -a; \
    elif [ `which apk` ]; then apk update && apk add --no-cache python sudo bash ca-certificates; \
    elif [ `which xbps-install` ]; then xbps-install -Syu && xbps-install -y python sudo bash ca-certificates && xbps-remove -O; fi

RUN if [ `which systemctl` ]; \
    then \
      rm -f /lib/systemd/system/sysinit.target.wants/systemd-tmpfiles-setup.service; \
      rm -f /lib/systemd/system/multi-user.target.wants/*;\
      rm -f /etc/systemd/system/*.wants/*;\
      rm -f /lib/systemd/system/local-fs.target.wants/*; \
      rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
      rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
      rm -f /lib/systemd/system/basic.target.wants/*; \
      rm -f /lib/systemd/system/anaconda.target.wants/*; \
    fi;

VOLUME ["/sys/fs/cgroup"]
CMD ["/lib/systemd/systemd"]