---
name: CI

on:
  pull_request:
  schedule:
    - cron: "13 5 15 * *"

jobs:

  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.4

      - name: Lint Code Base
        uses: github/super-linter@v3.17.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ANSIBLE_DIRECTORY: /
          VALIDATE_ANSIBLE: false

  molecule:
    needs: lint
    name: Molecule
    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v2.3.4

      - name: Run Molecule via Tox
        uses: actions/setup-python@v2.2.2
        with:
          python-version: "3.x"
        run: |
          pip3 install tox
          tox
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
